// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEI7gaOCPxGVjQQ_rICyOJO4mLrwmafAA',
    appId: '1:1056162533471:web:27ca81482a38dd0668cbea',
    messagingSenderId: '1056162533471',
    projectId: 'fcm-test-940916',
    authDomain: 'fcm-test-940916.firebaseapp.com',
    storageBucket: 'fcm-test-940916.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGUYVsswctCCjSbdpD-S1ZQ__DEaqp2s',
    appId: '1:1056162533471:android:bffa642069d9200a68cbea',
    messagingSenderId: '1056162533471',
    projectId: 'fcm-test-940916',
    storageBucket: 'fcm-test-940916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zuaEgHfR5NTUyoFz-AlpxClVlBkpcJI',
    appId: '1:1056162533471:ios:e835a2eaa742ef5468cbea',
    messagingSenderId: '1056162533471',
    projectId: 'fcm-test-940916',
    storageBucket: 'fcm-test-940916.appspot.com',
    iosClientId: '1056162533471-9ddaifitbt4n2rmu29vvnnbhj8l920ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
